## 1.3.1 Задание
### Задача:
<p>Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [1]:
import numpy as np
Z = np.zeros((8,8), dtype = int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 1.3.2 Задание
### Задача:
<p>Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [2]:
import numpy as np
Z = np.zeros((5,5), dtype = int)
Z += np.arange(5)
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [3]:
import numpy as np
Z = np.random.random((3, 3, 3))
print(Z)

[[[0.49765895 0.60494169 0.8907764 ]
  [0.32417909 0.32300483 0.77449789]
  [0.22811357 0.06968791 0.14196384]]

 [[0.43782988 0.35534928 0.81918218]
  [0.03816934 0.76337893 0.77226599]
  [0.66393805 0.99057324 0.49170294]]

 [[0.08329662 0.51255178 0.05376808]
  [0.27736777 0.94734657 0.95820669]
  [0.22550157 0.94471577 0.44274419]]]


In [4]:
import numpy as np
matrix = np.zeros((10, 10))
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1
print(matrix)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [5]:
import numpy as np
arr = np.random.random(10)
print(sorted(arr, reverse=True))

[np.float64(0.9468380923283215), np.float64(0.8405621709256671), np.float64(0.7943280923064745), np.float64(0.7892599047241142), np.float64(0.6400619888216188), np.float64(0.49491581181091826), np.float64(0.4884637194314041), np.float64(0.24116587522060073), np.float64(0.20808435546608017), np.float64(0.02784114919829872)]


In [6]:
import numpy as np
matrix = np.zeros((5, 10))
print("Форма матрицы:", matrix.shape)
print("Размер матрицы:", matrix.size)
print("Размерность матрицы:", matrix.ndim)

Форма матрицы: (5, 10)
Размер матрицы: 50
Размерность матрицы: 2


In [1]:
!pip install pandas

In [5]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/refs/heads/main/adult.csv'
dataframe = pd.read_csv(url)

In [3]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/refs/heads/main/adult.csv'
dataframe = pd.read_csv(url)
print(dataframe.head(2))
print(dataframe.tail(3))
print(dataframe.shape)
print(dataframe.describe())
print(dataframe.iloc[1:4])
print(dataframe[dataframe['age'] == 39].head(2))

   age         workclass  education_num      marital_status       occupation  \
0   39         State-gov             13       Never-married     Adm-clerical   
1   50  Self-emp-not-inc             13  Married-civ-spouse  Exec-managerial   

    relationship   race gender  hours_per_week native_country  capital  \
0  Not-in-family  White   Male              40  United-States     2174   
1        Husband  White   Male              13  United-States        0   

  income_status  
0         <=50K  
1         <=50K  
       age     workclass  education_num      marital_status       occupation  \
45219   38       Private             13  Married-civ-spouse   Prof-specialty   
45220   44       Private             13            Divorced     Adm-clerical   
45221   35  Self-emp-inc             13  Married-civ-spouse  Exec-managerial   

      relationship   race gender  hours_per_week native_country  capital  \
45219      Husband  White   Male              50  United-States        0   
45220    

In [4]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
x = np.array(dataframe['sepal_length_cm']).reshape(-1, 1)
x2 = np.array(dataframe['sepal_width_cm']).reshape(-1, 1)
minmax_scale = preprocessing.MinMaxScaler()
scaled_feature = minmax_scale.fit_transform(x)
print("sepal_length_cm с использованием минимаксного преобразования \n\n",scaled_feature,"\n")
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x2)
print("sepal_width_cm с задействованием z-масштабирования \n\n",standardized)

sepal_length_cm с использованием минимаксного преобразования 

 [[0.22222222]
 [0.16666667]
 [0.11111111]
 [0.08333333]
 [0.19444444]
 [0.30555556]
 [0.08333333]
 [0.19444444]
 [0.02777778]
 [0.16666667]
 [0.30555556]
 [0.13888889]
 [0.13888889]
 [0.        ]
 [0.41666667]
 [0.38888889]
 [0.30555556]
 [0.22222222]
 [0.38888889]
 [0.22222222]
 [0.30555556]
 [0.22222222]
 [0.08333333]
 [0.22222222]
 [0.13888889]
 [0.19444444]
 [0.19444444]
 [0.25      ]
 [0.25      ]
 [0.11111111]
 [0.13888889]
 [0.30555556]
 [0.25      ]
 [0.33333333]
 [0.16666667]
 [0.19444444]
 [0.33333333]
 [0.16666667]
 [0.02777778]
 [0.22222222]
 [0.19444444]
 [0.05555556]
 [0.02777778]
 [0.19444444]
 [0.22222222]
 [0.13888889]
 [0.22222222]
 [0.08333333]
 [0.27777778]
 [0.19444444]
 [0.75      ]
 [0.58333333]
 [0.72222222]
 [0.33333333]
 [0.61111111]
 [0.38888889]
 [0.55555556]
 [0.16666667]
 [0.63888889]
 [0.25      ]
 [0.19444444]
 [0.44444444]
 [0.47222222]
 [0.5       ]
 [0.36111111]
 [0.66666667]
 [0.36111111